### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by AdrienLemaire** [andreioprisan/meteor-newrelic#1]
Hello,

Thank you for making a package for newrelic.
But where should I set the license key provided by newrelic, that allow them to validate our app ? Is there a file to copy to the root directory of my project, and some value to edit ?

Thanks for your help
Cordially

**Comment by AdrienLemaire** [comment]
bump on this card

**Comment by PoBuchi** [comment]
hi,
good question, as I am struggling with NewRelic as well. I couldn't figure out their to put configuration file.It will be very helpful if you share your solution.
Thanks,
Pauli

**Comment by AdrienLemaire** [comment]
The maintainer must be very busy, or forgot about that issue.
This is very annoying, I can't run meteor with error:

```
W20140123-17:46:23.931(11)? (STDERR) Error: Unable to find New Relic module configuration. A default
W20140123-17:46:23.931(11)? (STDERR) configuration file can be copied from /home/hdd/.meteorite/packages/meteor-newrelic/andreioprisan/meteor-newrelic/54131ffaa2f47533339959bd296557ccb692e314/.build/npm/node_modules/newrelic/lib/config.default.js
W20140123-17:46:23.931(11)? (STDERR) and put at /home/dori/Projects/CoinsManager/.meteor/local/build/programs/server/newrelic.js or
W20140123-17:46:23.931(11)? (STDERR) /home/dori/Projects/CoinsManager/.meteor/local/build/newrelic.js.
```

but when I add the newrelic.js file there, it gets deleted as soon as I restart meteor, and this error is raised again

**Comment by andreioprisan** [comment]
Sorry about the delay, been very busy lately. :/ I will try to be more responsive in the future. 

The issue with the newrelic package from the npm package authors (https://npmjs.org/package/newrelic) is that they require these steps to get the package working correctly:

```
Copy newrelic.js from node_modules/newrelic into the root directory of your application.
Edit newrelic.js and replace license_key's value with the license key for your account.
```

Obviously, this cannot be done through any public or private meteor APIs for package management.
The only way to get this package working correctly (and this is the way that I got it to work) is to have a script that goes onto the bundled meteor application folder itself and modifies the newrelic.js file in the packages/newrelic folder to provide that license ID.

Ideally, the newrelic folks will update their node package to be more accessible from a configuration standpoint and just allow for an environmental variable readout, similar to how you can set the mongo or port string in meteor.
I opened a ticket with them and hoping that they will follow through: https://github.com/newrelic/node-newrelic/issues/110. Please upvote that issue to get more traction on getting this closed out and working for everyone. For now, you'll have to either remove the package or do your own post-bundle configuration magic.

**Comment by andreioprisan** [comment]
It looks like the node-newrelic package does support external configuration options and I have updated the README to specify those required options, as well as a link to all the options from the package itself.
All you have to do is set those env variables and the newrelic package will work.
